name: Orlando Portfolio
favicon: null
layout_spectrum: 0.9234043
typography_spectrum: 0.52733
title: oPortfolio
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#7f216d'
    - '#01508b'
    - '#cca2c1'
    - '#d65e00'
  brandStrength: 0.8125
  lightness: 0.6875
  saturation: 0.9375
  rhythmicContrast: 0.75
purpose: []
