name: Orlando Portfolio
favicon: null
layout_spectrum: 0.4417972578667104
typography_spectrum: 0.6145089704077691
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.5917637329548597
  lightness: 0.44137115054763854
  saturation: 0.8921432557981461
  rhythmicContrast: 0.32664681202732027
purpose: []
