name: Orlando Portfolio
favicon: null
layout_spectrum: 0.4417972578667104
typography_spectrum: 0.52733
title: Orlando.Portfolio
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.6875
  lightness: 0.44137115054763854
  saturation: 0.9375
  rhythmicContrast: 0.75
purpose: []
